version: 2

sources:
  - name: dbt_artifacts
    overrides: dbt_artifacts
    schema: "{{ target.schema }}"
    freshness:
      error_after: {count: 24, period: hour}
    loaded_at_field: current_timestamp
